spring:
  cloud:
    function:
      definition: employeeConsumer;employersList
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: fenix000
    url: jdbc:postgresql://localhost:5432/serverless